### ISSUE TITLE
support for viewing comments

### ISSUE THREAD

**Issue by FND** [jsmits/github-cli#33]
As far as I can tell, there is currently no way to retrieve a ticket's comments through _ghi_.

I've made a basic attempt at adding this functionality:
http://github.com/FND/github-cli/commit/b8fe26fa727a9b239c4d6f195c63f9aded50c559
It's probably not suitable to be merged in its current form though. Please let me know if you have any suggestions on how to improve it.

**Comment by jsmits** [comment]
Actually, I was thinking about how to do this myself the other day. I think your solution might be a first step in the right direction, albeit a little rough around the edges. Unfortunately, the last time I looked at the API, it was not possible to know whether an issue has comments. That's too bad, I think, because then you always have to do two requests. But anyway, that's what we've got to deal with, until the API exposes that functionality. Another suggestion to you would be to write the comments with the Pager like in the `list` command. That way you can browse through a long list of comments more easily. And it would be better to create a `format_comment` function, like the `format_issue` function, to make sure it is displayed nicely and textwrapped and all. Is it possible for you to update your fork with the code I committed after you forked? Also, I was thinking about something like this: `ghi 28 -v` would show comments and `ghi 28` would not. I'm not sure about this though, what do you think?

**Comment by FND** [comment]
> write the comments with the Pager like in the `list` command
> 
> it would be better to create a `format_comment` function, like the `format_issue` function
> 
> I was thinking about something like this: `ghi 28 -v` would show comments and `ghi 28` would not.

This all seems sensible - will look into implementing these enhancements and send a pull request when ready (unless you feel like implementing it yourself?).

> Is it possible for you to update your fork with the code I committed after you forked?

Yes, that's rather easy:

```
$ git remote add upstream git://github.com/jsmits/github-cli.git
$ git pull upstream master
```

I should be up to date already:
http://github.com/FND/github-cli/compare/1b31bb1218...d9fbda954f

> Unfortunately, the last time I looked at the API, it was not possible to know whether an issue has comments.

Still the same. I've put in a [request](http://support.github.com/discussions/feature-requests/765-issues-api-has_comments-flag), but I guess it's not a big deal for the moment, and should be easy to improve once such a flag is available.

**Comment by jsmits** [comment]
Sound good to me, feel free to implement these enhancements. Just let me know when to pull and I'll look into it. Of course, you can always contact me, If you have any questions in the meantime.

**Comment by FND** [comment]
I've sent you a pull request for the following:
http://github.com/FND/github-cli/compare/d9fbda954f...f8f7d2d049

There's some potential for refactoring of the output generation, but I chose not to do that here to avoid obscuring the diff with unrelated changes.
