### ISSUE TITLE
when opening a new issue, do not comment out the lines starting with #

### ISSUE THREAD

**Issue by roktas** [jsmits/github-cli#36]
#### Why?

Because one may want to enter text in "github flavored markdown" syntax (as in this issue text).

Using another character other than the `#` could be a solution.  Or at least adding a new command line option to disable this feature.

**Comment by jsmits** [comment]
I don't think changing to another character other than `#` would be a good solution for this. A command-line option could be a solution, e.g.: `ghi open --gfm` or something like that, but I'm not sure about adding this feature, because I don't want to add too much options anymore. But, I'll leave this issue open for awhile: if there are more people that want this feature, I'll consider implementing it.

**Comment by jsmits** [comment]
Closed, because no one else wanted this feature for the last 6 months.
